name = "RadiiPolynomial"
version = "0.1.0"
defaultTargets = ["RadiiPolynomial"]

[[lean_lib]]
name = "RadiiPolynomial"
srcDir = "LEAN-modules"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
